[package]
name = "microdotphat"
description = "Driver for the MicrodotPHAT"
version = "0.2.1"
license = "MIT"
edition = "2021"

[dependencies]
embedded-hal = "1.0.0"

[dev-dependencies]
rppal = { version = "0.22.1", features = ["hal"] }
